package com.openiv.backend.api;

import com.openiv.backend.api.health.HealthHandler;
import com.openiv.backend.api.v1.V1Router;
import com.openiv.backend.auth.service.AccessRequestService;
import com.openiv.backend.auth.service.AuthService;
import com.openiv.backend.team.TeamService;
import com.openiv.backend.cases.CaseService;
import com.openiv.backend.transactions.TransactionService;
import com.openiv.backend.thresholds.ThresholdService;
import com.openiv.backend.beam.BeamService;
import com.openiv.backend.dashboard.DashboardService;
import com.openiv.backend.geofence.GeoFenceService;
import com.openiv.backend.heatmap.HeatmapService;
import com.openiv.backend.kyc.KycService;
import com.openiv.backend.webhooks.WebhookService;
import com.openiv.backend.config.AppConfig;
import com.openiv.backend.customers.CustomerService;
import com.openiv.backend.security.ContentTypeGuard;
import com.openiv.backend.security.Cors;
import com.openiv.backend.security.MethodGuard;
import com.openiv.backend.security.RateLimit;
import com.openiv.backend.security.RequestId;
import com.openiv.backend.security.SecurityConfig;
import com.openiv.backend.security.SecurityHeaders;
import io.vertx.core.Handler;
import io.vertx.core.Vertx;
import io.vertx.ext.web.Router;
import io.vertx.ext.web.RoutingContext;
import io.vertx.ext.web.handler.BodyHandler;
import io.vertx.ext.web.handler.ResponseTimeHandler;
import io.vertx.ext.web.handler.TimeoutHandler;
import io.vertx.sqlclient.Pool;

/**
 * Top-level HTTP router.
 *
 * <p>
 * <b>Middleware order matters.</b> We install in this sequence so cheap
 * rejections happen
 * before expensive work:
 * <ol>
 * <li>{@link RequestId} — every downstream log line / audit entry needs the
 * correlation ID.</li>
 * <li>{@link SecurityHeaders} — headers are set on the response object early;
 * later handlers
 * may end the response, so we do this before any {@code .end()} path.</li>
 * <li>{@link MethodGuard} — drop {@code TRACE}/{@code CONNECT} before anything
 * else looks at
 * the request.</li>
 * <li>{@link Cors} — preflight {@code OPTIONS} must short-circuit before
 * auth/rate-limit.</li>
 * <li>{@link RateLimit} — reject 429 before we parse the body or touch the
 * DB.</li>
 * <li>{@link BodyHandler} — bounded; enforces
 * {@link SecurityConfig#maxBodyBytes}.</li>
 * <li>{@link ContentTypeGuard} — must run after BodyHandler so streaming
 * uploads don't slip by.</li>
 * <li>{@link TimeoutHandler} — a hard per-request deadline.</li>
 * <li>{@link ResponseTimeHandler} — observability only.</li>
 * <li>Health endpoints — unauthenticated, required for LB probes.</li>
 * <li>{@code /api/v1/*} — auth gate applied inside the sub-router so future
 * public v1
 * endpoints can opt out if needed.</li>
 * <li>{@link ErrorHandler} — final safety net; no stack or message
 * leakage.</li>
 * </ol>
 *
 * <p>
 * Per-request access logging via {@code LoggerHandler} is deliberately omitted:
 * at high RPS
 * it's a measurable CPU cost and logs will be generated by the load balancer
 * anyway. Security
 * events flow through {@link com.openiv.backend.security.AuditLog} instead.
 */
public final class ApiRouter {

  private ApiRouter() {
  }

  public static void mount(Vertx vertx, Router router, Pool dbPool, SecurityConfig security,
      AuthService authService, AccessRequestService accessRequestService,
      TeamService teamService, TransactionService transactionService,
      CaseService caseService, ThresholdService thresholdService,
      WebhookService webhookService, boolean devMode, BeamService beamService,
      KycService kycService, HeatmapService heatmapService,
      DashboardService dashboardService, GeoFenceService geoFenceService,
      CustomerService customerService,
      com.openiv.backend.workflows.WorkflowService workflowService,
      AppConfig.CloudinaryConfig cloudinaryConfig,
      AppConfig.BillingConfig billingConfig,
      AppConfig.AiConfig aiConfig,
      AppConfig.WebAuthnConfig webAuthnConfig,
      AppConfig.RedisConfig redisConfig) {
    router.route().handler(RequestId.create());
    if (devMode) {
      router.route().handler(com.openiv.backend.security.RequestDebugLogger.create());
    }
    router.route().handler(SecurityHeaders.create(security));
    router.route().handler(MethodGuard.create());
    router.route().handler(Cors.create(security));
    router.route().handler(RateLimit.create(security));
    // Document upload needs a larger body limit; register before the global handler.
    // BodyHandler is idempotent — the global handler below is a no-op for this path.
    router.post("/api/v1/documents/upload")
        .handler(BodyHandler.create().setBodyLimit(10L * 1024 * 1024).setHandleFileUploads(true));
    // Signing credentials: accept either multipart file upload or base64 JSON — 5 MB limit.
    router.patch("/api/v1/institution/signing-credentials")
        .handler(BodyHandler.create().setBodyLimit(5L * 1024 * 1024)
            .setHandleFileUploads(true).setUploadsDirectory("uploads/tmp"));
    // KYC beam stream may include a selfie file upload — allow up to 5 MB.
    router.post("/api/v1/beam/kyc/stream")
        .handler(BodyHandler.create().setBodyLimit(5L * 1024 * 1024).setHandleFileUploads(true));
    // Workflow import: multipart/form-data with customers JSON + per-customer selfie files.
    // 20 MB covers a batch of ~10 customers each with a ~2 MB selfie.
    router.post("/api/v1/workflows/:id/import")
        .handler(BodyHandler.create().setBodyLimit(20L * 1024 * 1024)
            .setHandleFileUploads(true).setUploadsDirectory("uploads/tmp"));
    // Avatar upload needs multipart handling — register before the global body handler.
    router.post("/api/v1/auth/profile/avatar")
        .handler(BodyHandler.create().setBodyLimit(5L * 1024 * 1024).setHandleFileUploads(true)
            .setUploadsDirectory("uploads/tmp"));
    // CBN policy PDF upload for AI rule template suggestions — up to 20 MB.
    router.post("/api/v1/nomos/suggest")
        .handler(BodyHandler.create().setBodyLimit(20L * 1024 * 1024)
            .setHandleFileUploads(true).setUploadsDirectory("uploads/tmp"));
    // Institution logo upload — up to 2 MB image.
    router.post("/api/v1/institution/logo")
        .handler(BodyHandler.create().setBodyLimit(2L * 1024 * 1024)
            .setHandleFileUploads(true).setUploadsDirectory("uploads/tmp"));
    router.route().handler(BodyHandler.create().setBodyLimit(security.maxBodyBytes()));
    router.route().handler(ContentTypeGuard.create());
    // SSE stream must not be subject to the per-request timeout — bypass it for that path.
    Handler<RoutingContext> timeout = TimeoutHandler.create(security.requestTimeoutMillis(), 503);
    router.route().handler(ctx -> {
      String path = ctx.normalizedPath();
      if (path != null && (path.endsWith("/dashboard/events")
          || path.endsWith("/dashboard/stream")
          || path.endsWith("/activity-stream")
          || path.endsWith("/otp-alerts-stream")
          || path.endsWith("/beam/kyc/stream")
          || path.contains("/geo-access/requests/") && path.endsWith("/watch")
          || path.endsWith("/ws/session")
          || path.endsWith("/comprehend")
          || path.endsWith("/generate")
          || path.endsWith("/nomos/templates")
          || path.endsWith("/nomos/suggest")
          || path.endsWith("/chat/eureka/stream"))) ctx.next();
      else timeout.handle(ctx);
    });
    router.route().handler(ResponseTimeHandler.create());

    HealthHandler.mount(router);
    // Serve uploaded files (avatars, etc.) as static assets.
    router.route("/uploads/*").handler(
        io.vertx.ext.web.handler.StaticHandler.create(io.vertx.ext.web.handler.FileSystemAccess.RELATIVE, "uploads")
            .setCachingEnabled(true)
            .setMaxAgeSeconds(86400)
            .setDirectoryListing(false));
    router.route("/api/v1/*").subRouter(V1Router.create(
        vertx, dbPool, security, authService, accessRequestService,
        teamService, transactionService, caseService, thresholdService, webhookService, devMode,
        beamService, kycService, heatmapService, dashboardService, geoFenceService,
        customerService, workflowService, cloudinaryConfig, billingConfig, aiConfig, webAuthnConfig,
        redisConfig));

    if (devMode) {
      com.openiv.backend.api.dev.DocsHandler.mount(router);
    }

    router.route().failureHandler(ErrorHandler::handle);
  }
}
