-- V59: Remove seeded behavioral rules.
-- Behavioral rules are now configured per-institution via the Behavioral Patterns API.
-- Institutions manage their own rules without default seeds.

DELETE FROM behavioral_rules
WHERE rule_id IN (
    'LOGIN_TIME_ANOMALY',
    'LOGIN_VELOCITY',
    'LOGIN_IMPOSSIBLE_TRAVEL',
    'LOGIN_NEW_COUNTRY',
    'LOGIN_TIMESTAMP_STALE',
    'LOGIN_TIMESTAMP_FUTURE',
    'LOGIN_MICRO_TIMING',
    'ACTIVITY_TIME_ANOMALY',
    'ACTIVITY_BURST',
    'ACTIVITY_TIMESTAMP_STALE',
    'ACTIVITY_TIMESTAMP_FUTURE',
    'ACTIVITY_MICRO_TIMING',
    'ACTIVITY_SESSION_ANOMALY',
    'LOCATION_IMPOSSIBLE_TRAVEL',
    'LOCATION_HIGH_RISK_REGION',
    'LOCATION_TIMESTAMP_STALE',
    'LOCATION_TIMESTAMP_FUTURE',
    'LOCATION_MICRO_TIMING',
    'LOCATION_RAPID_CHANGE',
    'LOCATION_COUNTRY_CHANGE',
    'DEVICE_SHARED_ACCOUNTS',
    'DEVICE_JAILBREAK_ROOT',
    'DEVICE_EMULATOR',
    'DEVICE_TIMESTAMP_STALE',
    'DEVICE_TIMESTAMP_FUTURE',
    'DEVICE_MICRO_TIMING',
    'DEVICE_RAPID_SWAP',
    'DEVICE_CLONED',
    'OTP_TIMESTAMP_STALE',
    'OTP_TIMESTAMP_FUTURE',
    'OTP_MICRO_TIMING'
);
